weights: runs/train/yolov5s_results5/weights/last.pt
cfg: ./models/custom_yolov5s.yaml
data: ../data.yaml
hyp: data/hyp.scratch.yaml
epochs: 800
batch_size: 16
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov5s_results52
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5s_results52
total_batch_size: 16
